package httpapi

import (
	"context"
	"net/http"

	"github.com/Mesteriis/rune-terminal/core/app"
)

type API struct {
	runtime   *app.Runtime
	authToken string
}

func NewHandler(runtime *app.Runtime, authToken string) http.Handler {
	api := &API{runtime: runtime, authToken: authToken}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", api.handleHealth)
	mux.HandleFunc("GET /api/v1/health", api.handleHealth)
	mux.HandleFunc("GET /api/v1/bootstrap", api.handleBootstrap)
	mux.HandleFunc("GET /api/v1/workflow/quick-actions", api.handleQuickActions)
	mux.HandleFunc("GET /api/v1/workspace", api.handleWorkspace)
	mux.HandleFunc("GET /api/v1/workspaces", api.handleListWorkspaces)
	mux.HandleFunc("GET /api/v1/workspaces/themes", api.handleWorkspaceThemes)
	mux.HandleFunc("GET /api/v1/workspace/widget-kinds", api.handleWorkspaceWidgetKinds)
	mux.HandleFunc("POST /api/v1/workspaces", api.handleCreateWorkspace)
	mux.HandleFunc("PATCH /api/v1/workspaces/{workspaceID}", api.handleUpdateWorkspaceMetadata)
	mux.HandleFunc("DELETE /api/v1/workspaces/{workspaceID}", api.handleDeleteWorkspace)
	mux.HandleFunc("POST /api/v1/workspaces/{workspaceID}/activate", api.handleActivateWorkspace)
	mux.HandleFunc("GET /api/v1/fs/list", api.handleListFS)
	mux.HandleFunc("GET /api/v1/fs/read", api.handleReadFS)
	mux.HandleFunc("GET /api/v1/fs/file", api.handleReadFSFile)
	mux.HandleFunc("PUT /api/v1/fs/file", api.handleWriteFSFile)
	mux.HandleFunc("POST /api/v1/fs/open", api.handleOpenFSExternal)
	mux.HandleFunc("POST /api/v1/fs/mkdir", api.handleMkdirFS)
	mux.HandleFunc("POST /api/v1/fs/copy", api.handleCopyFS)
	mux.HandleFunc("POST /api/v1/fs/move", api.handleMoveFS)
	mux.HandleFunc("POST /api/v1/fs/delete", api.handleDeleteFS)
	mux.HandleFunc("POST /api/v1/fs/rename", api.handleRenameFS)
	mux.HandleFunc("GET /api/v1/connections", api.handleConnections)
	mux.HandleFunc("POST /api/v1/connections/{connectionID}/check", api.handleCheckConnection)
	mux.HandleFunc("PUT /api/v1/connections/active", api.handleSelectConnection)
	mux.HandleFunc("POST /api/v1/connections/ssh", api.handleSaveSSHConnection)
	mux.HandleFunc("GET /api/v1/remote/profiles", api.handleListRemoteProfiles)
	mux.HandleFunc("POST /api/v1/remote/profiles", api.handleSaveRemoteProfile)
	mux.HandleFunc("POST /api/v1/remote/profiles/import-ssh-config", api.handleImportRemoteProfilesFromSSHConfig)
	mux.HandleFunc("DELETE /api/v1/remote/profiles/{profileID}", api.handleDeleteRemoteProfile)
	mux.HandleFunc("GET /api/v1/remote/profiles/{profileID}/tmux-sessions", api.handleListRemoteProfileTmuxSessions)
	mux.HandleFunc("POST /api/v1/remote/profiles/{profileID}/session", api.handleCreateRemoteSessionFromProfile)
	mux.HandleFunc("GET /api/v1/mcp/servers", api.handleListMCPServers)
	mux.HandleFunc("GET /api/v1/mcp/catalog", api.handleListMCPCatalog)
	mux.HandleFunc("POST /api/v1/mcp/probe", api.handleProbeMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers", api.handleRegisterMCPServer)
	mux.HandleFunc("GET /api/v1/mcp/servers/{serverID}", api.handleGetMCPServer)
	mux.HandleFunc("PUT /api/v1/mcp/servers/{serverID}", api.handleUpdateMCPServer)
	mux.HandleFunc("DELETE /api/v1/mcp/servers/{serverID}", api.handleDeleteMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers/{serverID}/start", api.handleStartMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers/{serverID}/stop", api.handleStopMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers/{serverID}/restart", api.handleRestartMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers/{serverID}/enable", api.handleEnableMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/servers/{serverID}/disable", api.handleDisableMCPServer)
	mux.HandleFunc("POST /api/v1/mcp/invoke", api.handleInvokeMCP)
	mux.HandleFunc("POST /api/v1/workspace/focus-widget", api.handleFocusWidget)
	mux.HandleFunc("POST /api/v1/workspace/focus-tab", api.handleFocusTab)
	mux.HandleFunc("PATCH /api/v1/workspace/layout", api.handleUpdateLayout)
	mux.HandleFunc("POST /api/v1/workspace/layouts/save", api.handleSaveLayout)
	mux.HandleFunc("POST /api/v1/workspace/layouts/switch", api.handleSwitchLayout)
	mux.HandleFunc("POST /api/v1/workspace/tabs", api.handleCreateTerminalTab)
	mux.HandleFunc("POST /api/v1/workspace/widgets/split", api.handleCreateSplitTerminalWidget)
	mux.HandleFunc("POST /api/v1/workspace/widgets/open-directory", api.handleOpenDirectoryInNewBlock)
	mux.HandleFunc("POST /api/v1/workspace/widgets/open-preview", api.handleOpenPreviewInNewBlock)
	mux.HandleFunc("POST /api/v1/workspace/widgets/move-split", api.handleMoveWidgetBySplit)
	mux.HandleFunc("DELETE /api/v1/workspace/widgets/{widgetID}", api.handleCloseWidget)
	mux.HandleFunc("POST /api/v1/workspace/tabs/remote", api.handleCreateRemoteTerminalTab)
	mux.HandleFunc("PATCH /api/v1/workspace/tabs/{tabID}/rename", api.handleRenameTab)
	mux.HandleFunc("PATCH /api/v1/workspace/tabs/{tabID}/pinned", api.handleSetTabPinned)
	mux.HandleFunc("POST /api/v1/workspace/tabs/move", api.handleMoveTab)
	mux.HandleFunc("DELETE /api/v1/workspace/tabs/{tabID}", api.handleCloseTab)
	mux.HandleFunc("GET /api/v1/tools", api.handleTools)
	mux.HandleFunc("POST /api/v1/tasks", api.handleCreateTask)
	mux.HandleFunc("POST /api/v1/tasks/claim", api.handleClaimTask)
	mux.HandleFunc("POST /api/v1/tasks/{id}/done", api.handleMarkTaskDone)
	mux.HandleFunc("POST /api/v1/tasks/{id}/fail", api.handleMarkTaskFail)
	mux.HandleFunc("GET /api/v1/tasks/active", api.handleActiveTasksV1)
	mux.HandleFunc("GET /api/v1/tasks/stats", api.handleTaskStats)
	mux.HandleFunc("GET /api/v1/policy/trusted-rules", api.handleTrustedRules)
	mux.HandleFunc("GET /api/v1/policy/ignore-rules", api.handleIgnoreRules)
	mux.HandleFunc("GET /api/v1/agent", api.handleAgentCatalog)
	mux.HandleFunc("GET /api/v1/agent/providers", api.handleProviderCatalog)
	mux.HandleFunc("GET /api/v1/plugins", api.handleListPlugins)
	mux.HandleFunc("POST /api/v1/plugins/install", api.handleInstallPlugin)
	mux.HandleFunc("POST /api/v1/plugins/{pluginID}/enable", api.handleEnablePlugin)
	mux.HandleFunc("POST /api/v1/plugins/{pluginID}/disable", api.handleDisablePlugin)
	mux.HandleFunc("POST /api/v1/plugins/{pluginID}/update", api.handleUpdatePlugin)
	mux.HandleFunc("DELETE /api/v1/plugins/{pluginID}", api.handleDeletePlugin)
	mux.HandleFunc("GET /api/v1/settings/agent", api.handleAgentSettings)
	mux.HandleFunc("PUT /api/v1/settings/agent", api.handleUpdateAgentSettings)
	mux.HandleFunc("GET /api/v1/settings/terminal", api.handleTerminalSettings)
	mux.HandleFunc("PUT /api/v1/settings/terminal", api.handleUpdateTerminalSettings)
	mux.HandleFunc("GET /api/v1/agent/conversation", api.handleConversationSnapshot)
	mux.HandleFunc("GET /api/v1/agent/conversations", api.handleConversationList)
	mux.HandleFunc("POST /api/v1/agent/conversations", api.handleCreateConversation)
	mux.HandleFunc("PATCH /api/v1/agent/conversations/{conversationID}", api.handleRenameConversation)
	mux.HandleFunc("DELETE /api/v1/agent/conversations/{conversationID}", api.handleDeleteConversation)
	mux.HandleFunc("PUT /api/v1/agent/conversations/{conversationID}/archive", api.handleArchiveConversation)
	mux.HandleFunc("PUT /api/v1/agent/conversations/{conversationID}/restore", api.handleRestoreConversation)
	mux.HandleFunc("PUT /api/v1/agent/conversations/{conversationID}/context", api.handleUpdateConversationContext)
	mux.HandleFunc("PUT /api/v1/agent/conversations/{conversationID}/activate", api.handleActivateConversation)
	mux.HandleFunc("POST /api/v1/agent/providers", api.handleCreateProvider)
	mux.HandleFunc("POST /api/v1/agent/providers/models", api.handleDiscoverProviderModels)
	mux.HandleFunc("PATCH /api/v1/agent/providers/{providerID}", api.handleUpdateProvider)
	mux.HandleFunc("PUT /api/v1/agent/providers/active", api.handleSetActiveProvider)
	mux.HandleFunc("DELETE /api/v1/agent/providers/{providerID}", api.handleDeleteProvider)
	mux.HandleFunc("POST /api/v1/agent/conversation/messages", api.handleSubmitConversationMessage)
	mux.HandleFunc("POST /api/v1/agent/conversation/messages/stream", api.handleStreamConversationMessage)
	mux.HandleFunc("POST /api/v1/agent/conversation/streams/{streamID}/cancel", api.handleCancelConversationStream)
	mux.HandleFunc("GET /api/v1/agent/conversation/attachments/references", api.handleListAttachmentReferences)
	mux.HandleFunc("POST /api/v1/agent/conversation/attachments/references", api.handleCreateAttachmentReference)
	mux.HandleFunc("DELETE /api/v1/agent/conversation/attachments/references/{attachmentID}", api.handleDeleteAttachmentReference)
	mux.HandleFunc("POST /api/v1/agent/terminal-commands/plan", api.handlePlanTerminalCommand)
	mux.HandleFunc("POST /api/v1/agent/terminal-commands/explain", api.handleExplainTerminalCommand)
	mux.HandleFunc("GET /api/v1/execution/blocks", api.handleListExecutionBlocks)
	mux.HandleFunc("GET /api/v1/execution/blocks/{blockID}", api.handleGetExecutionBlock)
	mux.HandleFunc("PUT /api/v1/agent/selection/profile", api.handleSetActiveProfile)
	mux.HandleFunc("PUT /api/v1/agent/selection/role", api.handleSetActiveRole)
	mux.HandleFunc("PUT /api/v1/agent/selection/mode", api.handleSetActiveMode)
	mux.HandleFunc("POST /api/v1/tools/execute", api.handleExecuteTool)
	mux.HandleFunc("GET /api/v1/terminal/{widgetID}", api.handleTerminalSnapshot)
	mux.HandleFunc("GET /api/v1/terminal/{widgetID}/diagnostics", api.handleTerminalDiagnostics)
	mux.HandleFunc("POST /api/v1/terminal/{widgetID}/sessions", api.handleCreateTerminalSession)
	mux.HandleFunc("PUT /api/v1/terminal/{widgetID}/sessions/active", api.handleSetActiveTerminalSession)
	mux.HandleFunc("DELETE /api/v1/terminal/{widgetID}/sessions/{sessionID}", api.handleCloseTerminalSession)
	mux.HandleFunc("POST /api/v1/terminal/{widgetID}/input", api.handleTerminalInput)
	mux.HandleFunc("POST /api/v1/terminal/{widgetID}/interrupt", api.handleTerminalInterrupt)
	mux.HandleFunc("POST /api/v1/terminal/{widgetID}/restart", api.handleTerminalRestart)
	mux.HandleFunc("GET /api/v1/terminal/{widgetID}/stream", api.handleTerminalStream)
	mux.HandleFunc("GET /api/v1/audit", api.handleAudit)
	return api.withCORS(api.withAuth(mux))
}

func Shutdown(ctx context.Context, server *http.Server) error {
	return server.Shutdown(ctx)
}
